### ISSUE TITLE
Why do you choose Resilience4j

### ISSUE THREAD

**Issue by HelloTo4x** [MirAbbasAli/Telecomm#1]
Hi, i am reading your project, i have a question, why do u choose Resilience4j instead of Hystrix for Circuit Breaker ? Can u tell me the pros and cons of Resilienece4j

**Comment by MirAbbasAli** [comment]
Hystrix is not available any more starting from the 2020.0.0 release train. Resilience4J is a good replacement.
The following Spring Cloud Netflix modules and corresponding starters are placed into maintenance mode:
- spring-cloud-netflix-archaius
- spring-cloud-netflix-hystrix-contract
- spring-cloud-netflix-hystrix-dashboard
- spring-cloud-netflix-hystrix-stream
- spring-cloud-netflix-hystrix
- spring-cloud-netflix-ribbon
- spring-cloud-netflix-turbine-stream
- spring-cloud-netflix-turbine
- spring-cloud-netflix-zuul
