### ISSUE TITLE
Why do you use Consul

### ISSUE THREAD

**Issue by HelloTo4x** [MirAbbasAli/Telecomm#2]
Hi, i am reading your project, why do you choose Consul instead of Eureka or Zookeeper, can you tell me your purpose when using Consul, the pros and cons of Consul, thanks

**Comment by MirAbbasAli** [comment]
The existing open source work on eureka 2.0 is discontinued. The code base and artifacts that were released as part of the existing repository of work on the 2.x branch is considered to be used at our own risk. I haven't work with zookeeper yet, so haven't choose that for the project.
